 name: CI
  on:
    pull_request:
    push:
      branches: [main]

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v1
          with:
            bun-version: 1.2.23
        - run: bun install --frozen-lockfile
        - run: bun test
        - run: bun run build
